### PR TITLE
New Objective for LEED Daylight credit EQc7 Option 2

### PR DESCRIPTION
**Pull request by agonzalezesteve**
LEED credit EQc7 Option 2 needs to compute the percentage of the area that has an illuminance between 300 and 3000 lux at equinoxes.

A new objective is created following the structure of Groundhog.

A new gendaylit function is created that draws a sky distribution according to the irradiance data from the epw file.

### CODE REVIEW

**Comment by germolinal** [comment]
Hello, 

I am sorry! I did not receive any e-mail about this. Let me check this out and will merge very happily!

Thanks for contributing!

**Comment by germolinal** [comment]
Did you compile this into the RBZ file?

**Comment by agonzalezesteve** [comment]
No, I didn't.

**Comment by germolinal** [comment]
All right, I will do that soon.

Best

**Pull request merged**
